[package]
name = "neorv32"
version = "0.1.0"
edition = "2024"

[dependencies]
riscv = "0.13.0"
riscv-peripheral = "0.2.1"
riscv-rt = { version = "0.14.0", optional = true }
vcell = "0.1.3"

[features]
rt = ["riscv-rt"]
v-trap = ["rt", "riscv-rt/v-trap"]
