[package]
name = "ethernetlite_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
panic-halt = "1.0.0"
riscv-rt = "0.14.0"
neorv32 = { path = "../../shared/sw/neorv32" }
xilinx = { path = "../../shared/sw/xilinx" }
volatile-register = "0.2.2"
heapless = "0.8.0"
