[target.riscv32imac-unknown-none-elf]
rustflags = [
    "-C",
    "link-arg=-Tshared/sw/memory.x", # memory.x must appear BEFORE link.x
    "-C",
    "link-arg=-Tlink.x",
]

[build]
target = "riscv32imac-unknown-none-elf"
